---
- name: clojure - Verify if install clojure
  stat:
    path: /opt/clojure
  register: stat_result

- name: clojure - Download the installation file
  get_url:
    url: https://download.clojure.org/install/{{ clojure_file }}
    dest: /tmp
  when: stat_result.stat.exists == False

- name: clojure - chmod +x to the file
  shell: chmod +x /tmp/{{ clojure_file }}
  when: stat_result.stat.exists == False

- name: clojure - Run the installation files
  shell: /tmp/{{clojure_file }} --prefix /opt/clojure
  when: stat_result.stat.exists == False
  become: true

- name: leiningen - Link file to /usr/local/bin
  file: src=/opt/clojure/bin/{{ item }}
    dest=/usr/local/bin/{{ item }}
    state=link
    force=yes
  loop:
    - clj
    - clojure
  become: true
