---
- name: Docker pacman - Verify if load loop module
  stat:
    path: /etc/modules-load.d/loop.conf
  register: stat_result

- name: Docker pacman - Create loop.conf
  shell: tee /etc/modules-load.d/loop.conf <<< "loop"
  when: stat_result.stat.exists == False
  become: true

- name: Docker pacman - modprobe loop module
  shell: modprobe loop
  when: stat_result.stat.exists == False
  become: true

- name: Docker pacman - Make sure "docker" is present
  pacman: name=docker state=present
  when: stat_result.stat.exists == False
  become: true

- name: Docker pacman - start and enable on boot
  shell: systemctl start docker.service; systemctl enable docker.service
  when: stat_result.stat.exists == False
  become: true

- name: Docker pacman - add current user to the docker group
  shell: gpasswd -a {{ whoami }} docker
  when: stat_result.stat.exists == False
  become: true

- name: Docker pacman - Make sure "docker-compose" is present
  pacman: name=docker-compose state=present
  when: os_distro == "manjaro"
  become: true
