---
- name: Node pkgs (manjaro) - Installing global node pkgs for linux manjaro
  shell: if [[ ! -d "$HOME/.npm-global/lib/node_modules/{{ item }}" ]]; then npm install -g {{ item }}; else echo "ok"; fi
  loop:
    - meta
    - neovim
    - prettier
    - '@prettier/plugin-pug'
    - tern
    - typescript
    - ts-node
  environment:
    PATH: "{{ lookup('env', 'HOME') }}/.npm-global/bin:{{ ansible_env.PATH }}"
