---
- name: Snap pacman - Install snapd
  pacman: name=snapd state=present
  become: true

- name: Snap pacman - Enable systemctl
  shell: systemctl enable --now -f snapd.socket
  become: true

- name: Snap pacman - Install snap packages
  snap: name={{ item.name }} classic={{ item.classic }}
  loop:
    - { name: 'cmake', classic: true }
    - { name: 'snap-store', classic: false }
    - { name: 'spotify', classic: false }
  environment:
    PATH: "/var/lib/snapd/snap/bin:{{ ansible_env.PATH }}"
  become: true
