# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = nm-applet &
exec-once = hypridle
exec-once = fcitx5 -d
exec-once = hyprctl setcursor Bibata-Modern-Ice 24

exec-once = awww-daemon
exec-once = sh -c 'for i in $(seq 1 20); do awww query >/dev/null 2>&1 && break; sleep 0.25; done; awww img "$(find "$wallpaper_path" -type f | shuf -n 1)"'

exec-once = qs -c ~/.config/quickshell
