# https://wiki.hypr.land/Configuring/Variables/#input
input {
    kb_layout = us
    kb_variant = intl
    kb_model =
    kb_options= ctrl:nocaps
    kb_rules =

    follow_mouse = 0

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    scroll_factor = 0.4

    touchpad {
        natural_scroll = false
    }
}

# https://wiki.hypr.land/Configuring/Variables/#gestures
gesture = 3, horizontal, workspace

# Example per-device config
# See https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs for more
device {
    name = epic-mouse-v1
    sensitivity = -0.5
}