# See https://wiki.hypr.land/Configuring/Monitors/
#monitor=,preferred,auto,auto
monitor = HDMI-A-1,     preferred,       0x0, 1, transform, 0
monitor = DP-3,     1920x1080@165,    0x1080, 1, transform, 0
monitor = DP-2,     1920x1080@165, -1080x100, 1, transform, 3