# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

windowrule = match:class .*, suppress_event maximize

# opacity
windowrule = match:class ^(kitty).*$, opacity 0.80 0.80
windowrule = match:class ^(code).*$, opacity 0.95 0.95
windowrule = match:class ^(jetbrains-idea).*$, opacity 0.95 0.95
windowrule = match:class ^(spotify).*$, opacity 0.95 0.95
windowrule = match:class ^(vivaldi-stable).*$, opacity 1 0.90

# position
windowrule = match:title ^(Open File).*$, center on
windowrule = match:title ^(Open File).*$, float on
windowrule = match:title ^(Open Folder).*$, center on
windowrule = match:title ^(Open Folder).*$, float on
windowrule = match:title ^(Save As).*$, center on
windowrule = match:title ^(Save As).*$, float on
windowrule = match:class org.pulseaudio.pavucontrol, center on
windowrule = match:class org.pulseaudio.pavucontrol, float on
windowrule = match:class org.pulseaudio.pavucontrol, size (monitor_w*.45) (monitor_h*.85)
windowrule = match:title ^(Vivaldi Settings).*$, center on
windowrule = match:title ^(Vivaldi Settings).*$, float on
windowrule = match:title ^(Vivaldi Settings).*$, size (monitor_w*.45) (monitor_h*.85)

# workspaces
windowrule = match:class ^(code).*$, workspace 3
windowrule = match:class ^(spotify).*$, workspace 6
windowrule = match:class steam, workspace 6 silent
windowrule = match:class ^(steam_app_).*$, workspace 6 silent

# Steam
windowrule = match:class steam, opacity 0.80 0.80
windowrule = match:class steam, match:title ^(Friends List).*$, center on
windowrule = match:class steam, match:title ^(Friends List).*$, float on
windowrule = match:class steam, match:title ^(Friends List).*$, size (monitor_w*.30) (monitor_h*.65)
windowrule = match:class steam, match:title ^(Steam Settings).*$, center on
windowrule = match:class steam, match:title ^(Steam Settings).*$, float on
windowrule = match:class steam, match:title ^(Steam Settings).*$, size (monitor_w*.45) (monitor_h*.85)
windowrule = match:class ^(steam_app_).*$, immediate on
windowrule = match:class ^(steam_app_).*$, no_anim on
windowrule = match:class ^(steam_app_).*$, no_blur on
windowrule = match:class ^(steam_app_).*$, no_shadow on
windowrule = match:class ^(steam_app_).*$, rounding 0
windowrule = match:class ^(steam_app_).*$, fullscreen on
