# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Ignore maximize requests from all apps. You'll probably like this.
windowrule {
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

# Fix some dragging issues with XWayland
windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
# windowrule {
#     name = move-hyprland-run

#     match:class = hyprland-run

#     move = 20 monitor_h-120
#     float = yes
# }

windowrule {
    name = floating-pavucontrol
    match:class = org.pulseaudio.pavucontrol

    float = yes
    size = 900 900
    center = yes
}