- name: Emacs - Verify if install spacemacs
  stat:
    path: ~/.emacs.d
  register: verify_emacs

- name: Emacs - Download doom-emacs
  shell: warn=false git clone --depth 1 https://github.com/hlissner/doom-emacs ~/.emacs.d
  when: verify_emacs.stat.exists == False

- name: Emacs -  Install doom-emacs
  shell: warn=false ~/.emacs.d/bin/doom install
  when: verify_emacs.stat.exists == False
