---
- name: Fish - Get the current shell
  shell: echo $SHELL
  register: shell

# using sed to change the file, because had problem using chsh on wsl2
- name: Fish - Set the default shell to fish for linux
  shell: sed -i "s@{{ lookup('env', 'HOME') }}.*@{{ lookup('env', 'HOME') }}\:`which fish`@" /etc/passwd
  when: shell.stdout != "/bin/fish"
  become: true

- name: Fish - Verify if install fisher
  stat:
    path: ~/.config.old/fish/functions/fisher.fish
  register: verify_fisher

- name: Fish - Install fisher
  shell: warn=false fish -c "curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher"
  when: verify_fisher.stat.exists == False

- name: Fish - Install fisher plugins
  shell: if [[ ! -f "$HOME/.config.old/fish/functions/{{ item.fnpath }}" ]]; then fish -c "fisher install {{ item.plugin }}"; else echo "ok"; fi
  loop:
    - { fnpath: nvm.fish, plugin: jorgebucaran/nvm.fish }
    - { fnpath: fzf.fish, plugin: jethrokuan/fzf }
    - { fnpath: sdk.fish, plugin: reitzig/sdkman-for-fish@v1.4.0 }
