---
- name: Flutter - Verify if install flutter
  stat:
    path: /opt/flutter
  register: stat_result

- name: Flutter - Download flutter
  get_url:
    url: https://storage.googleapis.com/flutter_infra/releases/stable/linux/{{ flutter_tar_file }}
    dest: /tmp
  when: stat_result.stat.exists == False

- name: Flutter - Extract flutter to /tmp
  unarchive:
    src: /tmp/{{ flutter_tar_file }}
    dest: /tmp
  when: stat_result.stat.exists == False

- name: Flutter - Move flutter folder to /opt as /opt/flutter
  shell: mv /tmp/flutter /opt
  when: stat_result.stat.exists == False

- name: Flutter - Link binary file to /usr/local/bin
  file: src=/opt/flutter/bin/flutter
    dest=/usr/local/bin/flutter
    state=link
    force=yes
  when: stat_result.stat.exists == False
  become: true

- name: Flutter - Removing download file
  shell: warn=false rm /tmp/{{ flutter_tar_file }} 2>/dev/null
  when: stat_result.stat.exists == False

- name: Fix /opt/flutter permissions
  shell: chown -R {{ username }}:{{ usergroup }} /opt/flutter
  become: true
