---
- name: Paw - Verify if install paw
  stat:
    path: "/opt/Applications/paw-client-{{ paw_version}}_f2ba991e4a0f4254dc965b3e602611ee.AppImage"
  register: stat_result

- name: Paw - Download paw
  get_url:
    url: https://cdn-builds.paw.cloud/octopaw/{{ paw_version }}/9fec3db/linux/{{ paw_file }}
    dest: /tmp
  when: stat_result.stat.exists == False

- name: Paw - Change file permission to be executable
  file:
    path: /tmp/{{ paw_file }}
    mode: u+x
  when: stat_result.stat.exists == False

- name: Paw - execute AppImage to install it
  shell: /tmp/{{paw_file }}
  when: stat_result.stat.exists == False
