# Disable warnings from oh-my-zsh
ZSH_DISABLE_COMPFIX=true

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="fredericobenevides"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(brew bundler docker docker-compose docker-machine gem git go kubectl node npm oc pip postgres python fredericobenevides myutils)

# User configuration

export PATH=$HOME/bin:/usr/local/bin:$PATH
# export MANPATH="/usr/local/man:$MANPATH"

source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

export EDITOR='nvim'
export VISUAL='nvim'

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

alias docker_env_dev='eval $(docker-machine env dev)'
alias minishift_docker_env='eval $(minishift docker-env)'
alias minishift_oc_env='eval $(minishift oc-env)'

alias gotest="reflex -r '\.go$' -s go test ./..."
alias vim='nvim'

alias flutter_devtools='flutter pub global run devtools'

### GOLANG
export GOPATH="$HOME/code/go"
export PATH="$GOPATH/bin:$PATH"



### PYTHON
export PYTHONSTARTUP="$HOME/.pythonrc"



### ANACONDA
if [ -d "/opt/anaconda3" ]; then
  __conda_setup="$('/opt/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
  if [ $? -eq 0 ]; then
      eval "$__conda_setup"
  else
      if [ -f "/opt/anaconda3/etc/profile.d/conda.sh" ]; then
          . "/opt/anaconda3/etc/profile.d/conda.sh"
      else
          export PATH="/opt/anaconda3/bin:$PATH"
      fi
  fi
  unset __conda_setup
fi



### Android Studio
if [[ -d '/opt/Android/android-studio' ]]; then
  export ANDROID_HOME="/opt/Android/android-studio"
  export ANDROID_SDK="/opt/Android/Sdk"
  export PATH="$ANDROID_SDK/platform-tools:$ANDROID_SDK/tools:$ANDROID_SDK/tools/bin:$ANDROID_SDK/emulator:$PATH"
fi



### Flutter
if [[ -d '/opt/flutter' ]]; then
  export FLUTTER_HOME="/opt/flutter"
  export FLUTTER_PUB_CACHE="/opt/flutter/.pub-cache"
  export DART_HOME=/opt/flutter/bin/cache/dart-sdk

  export PATH="$DART_HOME/bin:$FLUTTER_PUB_CACHE/bin:$FLUTTER_HOME/bin:$PATH"
fi



### NODE
export PATH="$HOME/.npm-global/bin:$PATH"

if [ -d "/opt/node" ]; then
  export PATH="/opt/node/bin:$PATH"
fi



### RBENV
export RBENV_ROOT="${HOME}/.rbenv"

if [ -d "${RBENV_ROOT}" ]; then
  export PATH="${RBENV_ROOT}/bin:${PATH}"
  eval "$(rbenv init -)"
fi



### SNAP
if [[ -d /usr/lib/snapd ]]; then
  export PATH="/var/lib/snapd/snap/bin:${PATH}"
fi



### TMUX
# Work around when opening tmux to set the new environment to fix the colors
export TERM="xterm-256color"
if [ "$TMUX" ] && [ $TERM = "xterm-256color" ]; then
  export TERM="screen-256color"
fi



### FZF
export PATH="$PATH:$HOME/.fzf/bin"
export MANPATH="$MANPATH:$HOME/.fzf/man"
source "$HOME/.fzf/shell/completion.zsh" 2> /dev/null
source "$HOME/.fzf/shell/key-bindings.zsh"
export FZF_DEFAULT_COMMAND='ag --hidden --ignore .git --ignore node_modules -g ""'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_COMPLETION_TRIGGER='~~'



export PATH="$HOME/.local_scripts:$PATH"



export SDKMAN_DIR="/opt/sdkman"
[[ -s "/opt/sdkman/bin/sdkman-init.sh" ]] && source "/opt/sdkman/bin/sdkman-init.sh"



# Load local environment
if [ -f $HOME/.zshrc.local ]; then
  source $HOME/.zshrc.local
fi

