# debian

- name: Docker - Add ppa's docker for debian
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian {{ lookup('env','OS_CODENAME') }} stable
    state: present
  when: os_distro == "debian"
  become: true

- name: Docker - Add Docker's official GPG key for debian
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
  when: os_distro == "debian"
  become: true



# ubuntu
- name: Docker - Add ppa's docker for ubuntu
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ lookup('env','OS_CODENAME') }} stable
    state: present
  when: os_distro == "ubuntu"
  become: true

- name: Docker - Add Docker's official GPG key for ubuntu
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when: os_distro == "ubuntu"
  become: true



# common for debian and ubuntu

- name: Docker - Install Docker CE
  apt: name={{item}} state=present update_cache=true
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
  when: os_distro in ['debian', 'ubuntu']
  become: true

