---
- name: Node pkgs - Installing global node pkgs for macos
  npm: name=tern global=yes state=present
  loop:
    - meta
    - neovim
    - prettier
    - "@prettier/plugin-pug"
    - tern
    - typescript
    - ts-node
  when: os == "macos"

- name: Node pkgs (linux) - Installing global node pkgs for linux
  shell: /opt/node/bin/npm install -g {{ item }}
  environment:
    PATH: "/opt/node/bin:{{ ansible_env.PATH }}"
  loop:
    - meta
    - neovim
    - prettier
    - "@prettier/plugin-pug"
    - tern
    - typescript
    - ts-node
  when: (os == "linux") and (os_distro != "manjaro")
