- name: Ruby - Install rbenv for macos
  homebrew: name=rbenv state=present
  register: verify_rbenv
  when: os == "macos"

- name: Ruby - Install ruby for macos
  shell: eval "$(rbenv init -)"; rbenv install {{ ruby_version }}
  when: os == "macos" and verify_rbenv.changed

- name: Ruby - Define ruby {{ ruby_version }} as global for rbenv for macos
  shell: eval "$(rbenv init -)"; rbenv global {{ ruby_version }}
  when: os == "macos" and verify_rbenv.changed
