if has('nvim')
  call plug#begin('~/.local/share/nvim/plugged')
else
  call plug#begin('~/.vim/plugged')
endif

" Colors and themes {{{2
Plug 'joshdick/onedark.vim'
Plug 'bling/vim-airline'
" }}}2

" Editor Utilities {{{2
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'junegunn/vim-easy-align', { 'on': ['<Plug>(EasyAlign)', 'EasyAlign'] }
Plug 'majutsushi/tagbar'
Plug 'nathanaelkane/vim-indent-guides'
Plug 'Yggdroot/indentLine'
Plug 'terryma/vim-multiple-cursors'
Plug 'AndrewRadev/splitjoin.vim'
Plug 'easymotion/vim-easymotion'
Plug 'haya14busa/incsearch.vim'
Plug 'haya14busa/incsearch-easymotion.vim'
Plug 'fredericobenevides/line-mover.vim'
" }}}2

" FZF {{{2}}}
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': '~/.dotfiles/files/fzf/install.sh' }
Plug 'junegunn/fzf.vim'
" }}}2

" Git {{{2
Plug 'tpope/vim-fugitive'
Plug 'mattn/webapi-vim' | Plug 'mattn/gist-vim'
Plug 'junegunn/gv.vim'
" }}}2

" Go {{{2
Plug 'fatih/vim-go'
Plug 'sebdah/vim-delve'
Plug 'buoto/gotests-vim', { 'do': ':! go get -u github.com/cweill/gotests/...' }
" }}}2

" Html & css {{{2
Plug 'KabbAmine/vCoolor.vim'
" }}}2

" Syntax {{{2
Plug 'sheerun/vim-polyglot'
" }}}2

" Tpope Utilities {{{2
Plug 'tpope/vim-abolish'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-dispatch'
Plug 'tpope/vim-eunuch'
Plug 'tpope/vim-endwise'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-surround'

if has('nvim')
  Plug 'radenling/vim-dispatch-neovim'
endif
" }}}2

" Neovim's terminal integration {{{2
if has('nvim')
  Plug 'kassio/neoterm'
endif
" }}}2

call plug#end()
" }}}1

" Color and themes configs {{{1
syntax on
set t_Co=256
colorscheme onedark
set termguicolors " enable true colors in terminal
" }}}1

" Config settings {{{1

" Disable netrw {{{2
let g:loaded_netrw = 1
let g:loaded_netrwPlugin = 1
" }}}2

" Backup Settings {{{2
set nobackup
set nowritebackup
set noswapfile
" }}}2

" Buffer and Edit Settings {{{2
set autoread " Automatically read a file that has changed on disk
set backspace=indent,eol,start " backspace working like other apps
set cmdheight=2 " Give more space for displaying messages.
set hidden " Allow unsaved buffers to be put in background
set cursorline
set completeopt-=preview " stop showing the preview window using YCM
set cpoptions+=$ " put $ at the end of the changed word
let loaded_matchparen = 1 " disable the match for parentheses
set nrformats= " treat all numerals as decimal
set shortmess+=c " Don't pass messages to |ins-completion-menu|
set signcolumn=yes "Always show the signcolumn, otherwise it would shift the text each time diagnostics appear/become resolved
set updatetime=100 " change to 100ms for use with go_auto_type_info

" copy default to clipboard
if has('unnamedplus')
  set clipboard=unnamedplus
else
  set clipboard=unnamed
endif
" }}}2

" Enconding Settings {{{2
set encoding=utf-8
set fileencoding=utf-8
" }}}2

" Fold Settings {{{2
"set foldmethod=syntax
"set foldlevelstart=1
" }}}2

" History and Undo Settings {{{2
set history=1000
set undolevels=100
" }}}2

" Indent and Tab Settings {{{2
set autoindent " Copy indent from current line when starting a new line
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab
" }}}2

" List Settings {{{2
set list
set listchars=tab:»\ ,trail:·
" }}}2

" Mouse settings {{{2
set mousehide " hide the cursor while typing
set mouse=a " enable mouse inside vim
" }}}2

" Neovim's  Terminal settings {{{2
if has('nvim')
  highlight! link TermCursor Cursor
  highlight! TermCursorNC guibg=red guifg=white ctermbg=1 ctermfg=15
  highlight! Normal ctermfg=252 ctermbg=233 guifg=#F8F8F2 guibg=#1B1D1E " change background to be darker
endif
" }}}2

" Search Settings {{{2
set hlsearch " highlight all matches
set ignorecase " case of letters are ignore
set incsearch " while typing the pattern, show where it matches
set smartcase " override the ignorecase when search pattern has upper case
set scrolloff=5 " number of screen lines to keep above and below the cursor
" }}}2

" Split Settings {{{2
set splitbelow
set splitright
" }}}2

" Sound Settings {{{2
set noerrorbells
set visualbell
set vb t_vb= " this disable the sound and flash from noerrorbells and visualbell
" }}}2

" Wildmenu Settings {{{2
set wildmenu
set wildmode=list:longest,list:full
set wildignore+=*/tmp/*,*.so,*.swp,*.zip
" }}}2

" Window Settings {{{2
set title " Add the window title with the name of the file that is editing
set guioptions-=T " disable toolbar
set guioptions-=r " disable right-hand scrollbar
set guioptions-=L " disable left-hand scrollbar
set laststatus=2 " Always show the status line
set lazyredraw " don't update the display while executing macros
set number " show the current line number
set relativenumber " show the line number relative to the line with the cursor

if executable('ag')
  set grepprg=ag\ --nogroup\ --nocolor " Integrate with ag
endif
" }}}2

" Wrap Settings {{{2
set wrap
set textwidth=80
set formatoptions=qrn1
set colorcolumn=80
" }}}2
" }}}1

" Mappings {{{1

" Remap leader to <space> {{{2
let mapleader = " "
" }}}2

" Double spaces remove highlight {{{2
nnoremap <silent> <leader><space> :noh<cr>
" }}}2

" Disable Arrow Keys {{{2
inoremap <Up> <nop>
inoremap <Down> <nop>
inoremap <Left> <nop>
inoremap <Right> <nop>
" }}}2

" Mappings for F1-12 {{{2

" disable F1 to not call help
inoremap <F1> <ESC>
nnoremap <F1> <ESC>
vnoremap <F1> <ESC>

nnoremap <F6> :CocCommand explorer<CR>
nnoremap <F8> :TagbarOpenAutoClose<CR>
" }}}2

" Editing a file {{{2

" Remap Line motion commands
nnoremap k gk
nnoremap gk k
nnoremap j gj
nnoremap gj j

" Save current file
" nnoremap <leader>s :w<cr>
nnoremap <leader>s :call SaveCurrentBuffer()<cr>
nnoremap <c-s> :call SaveCurrentBuffer()<cr>

" Save all files
nnoremap <leader>S :wall<cr>

" Save files with sudo
cnoremap w!! w !sudo tee % >/dev/null

" Add ';' at the end of line
inoremap <leader>; <C-o>m`<C-o>A;<C-o>``

" Toggle Paste
nnoremap <leader>tp :set invpaste paste?<cr>
set pastetoggle=<leader>tp

" Toggle Wrap
nnoremap <leader>tw :set wrap! wrap?<cr>

" Find duplicate words
nnoremap <leader>fW /\v<(\w+)\_s+\1><cr>

" Find current word
nnoremap <leader>fw /\v<C-r><C-w><cr>

" Find and Substitute current word
nnoremap <leader>fs :%s/\v<C-r><C-w>

" Close tags
inoremap <// </<C-X><C-O>

" insert html tags
inoremap <c-e> <></><Esc>5hdiwp3lpT>i
nnoremap <c-e> a<></><Esc>5hdiwp3lpT>i
" }}}2

" Buffer Mappings {{{2

" Creating a new buffer
nnoremap <leader>bn :vnew<cr>  |" Open a new buffer in a new vertical window
nnoremap <leader>bN :new<cr>   |" Open a new buffer in a new horizontal window

" Deleting the buffer
nnoremap <leader>bd :bd<cr>   |" Delete the buffer
nnoremap <leader>bD :bd!<cr>  |" Forces to delete the buffer

" Moving around the buffers
nnoremap [b :bp<cr>              |" go to the previous buffer
nnoremap ]b :bn<cr>              |" go to the next buffer
nnoremap [B :bfirst<cr>          |" go to the first buffer
nnoremap ]B :blast<cr>           |" go to the last buffer
nnoremap <leader>bh :bp<cr>      |" Move to the previous buffer
nnoremap <leader>bl :bn<cr>      |" Move to the next buffer
nnoremap <leader>bH :bfirst<cr>  |" Move to the previous buffer
nnoremap <leader>bL :blast<cr>   |" Move to the next buffer
nnoremap <leader>ba <c-^><cr>    |" Alternate between buffers

" mark and move between marked buffers
nnoremap <silent> bm0 :call MarkBuffer('buffer_0')<cr>
nnoremap <silent> bm1 :call MarkBuffer('buffer_1')<cr>
nnoremap <silent> bm2 :call MarkBuffer('buffer_2')<cr>
nnoremap <silent> bm3 :call MarkBuffer('buffer_3')<cr>
nnoremap <silent> bm4 :call MarkBuffer('buffer_4')<cr>
nnoremap <silent> bm5 :call MarkBuffer('buffer_5')<cr>
nnoremap <silent> bm6 :call MarkBuffer('buffer_6')<cr>
nnoremap <silent> bm7 :call MarkBuffer('buffer_7')<cr>
nnoremap <silent> bm8 :call MarkBuffer('buffer_8')<cr>
nnoremap <silent> bm9 :call MarkBuffer('buffer_9')<cr>

nnoremap <silent> b0 :call OpenSplitBuffer('buffer_0', 0)<cr>
nnoremap <silent> b1 :call OpenSplitBuffer('buffer_1', 0)<cr>
nnoremap <silent> b2 :call OpenSplitBuffer('buffer_2', 0)<cr>
nnoremap <silent> b3 :call OpenSplitBuffer('buffer_3', 0)<cr>
nnoremap <silent> b4 :call OpenSplitBuffer('buffer_4', 0)<cr>
nnoremap <silent> b5 :call OpenSplitBuffer('buffer_5', 0)<cr>
nnoremap <silent> b6 :call OpenSplitBuffer('buffer_6', 0)<cr>
nnoremap <silent> b7 :call OpenSplitBuffer('buffer_7', 0)<cr>
nnoremap <silent> b8 :call OpenSplitBuffer('buffer_8', 0)<cr>
nnoremap <silent> b9 :call OpenSplitBuffer('buffer_9', 0)<cr>

nnoremap <silent> bs0 :call OpenSplitBuffer('buffer_0', 1)<cr>
nnoremap <silent> bs1 :call OpenSplitBuffer('buffer_1', 1)<cr>
nnoremap <silent> bs2 :call OpenSplitBuffer('buffer_2', 1)<cr>
nnoremap <silent> bs3 :call OpenSplitBuffer('buffer_3', 1)<cr>
nnoremap <silent> bs4 :call OpenSplitBuffer('buffer_4', 1)<cr>
nnoremap <silent> bs5 :call OpenSplitBuffer('buffer_5', 1)<cr>
nnoremap <silent> bs6 :call OpenSplitBuffer('buffer_6', 1)<cr>
nnoremap <silent> bs7 :call OpenSplitBuffer('buffer_7', 1)<cr>
nnoremap <silent> bs8 :call OpenSplitBuffer('buffer_8', 1)<cr>
nnoremap <silent> bs9 :call OpenSplitBuffer('buffer_9', 1)<cr>

nnoremap <silent> bt0 :call OpenTabBuffer('buffer_0')<cr>
nnoremap <silent> bt1 :call OpenTabBuffer('buffer_1')<cr>
nnoremap <silent> bt2 :call OpenTabBuffer('buffer_2')<cr>
nnoremap <silent> bt3 :call OpenTabBuffer('buffer_3')<cr>
nnoremap <silent> bt4 :call OpenTabBuffer('buffer_4')<cr>
nnoremap <silent> bt5 :call OpenTabBuffer('buffer_5')<cr>
nnoremap <silent> bt6 :call OpenTabBuffer('buffer_6')<cr>
nnoremap <silent> bt7 :call OpenTabBuffer('buffer_7')<cr>
nnoremap <silent> bt8 :call OpenTabBuffer('buffer_8')<cr>
nnoremap <silent> bt9 :call OpenTabBuffer('buffer_9')<cr>

nnoremap <silent> <c-Left> :call OpenDownMarkedBuffers()<cr>
nnoremap <silent> <c-Right> :call OpenUpMarkedBuffers()<cr>
" }}}2

" mark and move between marked terminals
nnoremap <silent> tm0 :call MarkBuffer('terminal_0')<cr>
nnoremap <silent> tm1 :call MarkBuffer('terminal_1')<cr>
nnoremap <silent> tm2 :call MarkBuffer('terminal_2')<cr>
nnoremap <silent> tm3 :call MarkBuffer('terminal_3')<cr>
nnoremap <silent> tm4 :call MarkBuffer('terminal_4')<cr>
nnoremap <silent> tm5 :call MarkBuffer('terminal_5')<cr>
nnoremap <silent> tm6 :call MarkBuffer('terminal_6')<cr>
nnoremap <silent> tm7 :call MarkBuffer('terminal_7')<cr>
nnoremap <silent> tm8 :call MarkBuffer('terminal_8')<cr>
nnoremap <silent> tm9 :call MarkBuffer('terminal_9')<cr>

nnoremap <silent> t0 :call OpenSplitBuffer('terminal_0', 0)<cr>
nnoremap <silent> t1 :call OpenSplitBuffer('terminal_1', 0)<cr>
nnoremap <silent> t2 :call OpenSplitBuffer('terminal_2', 0)<cr>
nnoremap <silent> t3 :call OpenSplitBuffer('terminal_3', 0)<cr>
nnoremap <silent> t4 :call OpenSplitBuffer('terminal_4', 0)<cr>
nnoremap <silent> t5 :call OpenSplitBuffer('terminal_5', 0)<cr>
nnoremap <silent> t6 :call OpenSplitBuffer('terminal_6', 0)<cr>
nnoremap <silent> t7 :call OpenSplitBuffer('terminal_7', 0)<cr>
nnoremap <silent> t8 :call OpenSplitBuffer('terminal_8', 0)<cr>
nnoremap <silent> t9 :call OpenSplitBuffer('terminal_9', 0)<cr>

nnoremap <silent> ts0 :call OpenSplitBuffer('terminal_0', 1)<cr>
nnoremap <silent> ts1 :call OpenSplitBuffer('terminal_1', 1)<cr>
nnoremap <silent> ts2 :call OpenSplitBuffer('terminal_2', 1)<cr>
nnoremap <silent> ts3 :call OpenSplitBuffer('terminal_3', 1)<cr>
nnoremap <silent> ts4 :call OpenSplitBuffer('terminal_4', 1)<cr>
nnoremap <silent> ts5 :call OpenSplitBuffer('terminal_5', 1)<cr>
nnoremap <silent> ts6 :call OpenSplitBuffer('terminal_6', 1)<cr>
nnoremap <silent> ts7 :call OpenSplitBuffer('terminal_7', 1)<cr>
nnoremap <silent> ts8 :call OpenSplitBuffer('terminal_8', 1)<cr>
nnoremap <silent> ts9 :call OpenSplitBuffer('terminal_9', 1)<cr>

nnoremap <silent> tt0 :call OpenTabBuffer('terminal_0')<cr>
nnoremap <silent> tt1 :call OpenTabBuffer('terminal_1')<cr>
nnoremap <silent> tt2 :call OpenTabBuffer('terminal_2')<cr>
nnoremap <silent> tt3 :call OpenTabBuffer('terminal_3')<cr>
nnoremap <silent> tt4 :call OpenTabBuffer('terminal_4')<cr>
nnoremap <silent> tt5 :call OpenTabBuffer('terminal_5')<cr>
nnoremap <silent> tt6 :call OpenTabBuffer('terminal_6')<cr>
nnoremap <silent> tt7 :call OpenTabBuffer('terminal_7')<cr>
nnoremap <silent> tt8 :call OpenTabBuffer('terminal_8')<cr>
nnoremap <silent> tt9 :call OpenTabBuffer('terminal_9')<cr>
" }}}2


" Windows Mappings {{{2

" Opening and closing a window
nnoremap <leader>wc <c-w>c     |" close the window
nnoremap <leader>wn :vnew<cr>  |" new horizontally window
nnoremap <leader>wN :new<cr>   |" new vertically window

" splitting current window
nnoremap <leader>ws <c-w><c-s><cr>  |" split curent window horizontally
nnoremap <leader>wv <c-w><c-v><cr>  |" split current window vertically

" change cursor around windows
nnoremap [w <c-w>W              |" go to the previous window
nnoremap ]w <c-w><c-w>          |" go to the next window
nnoremap <leader>wa <c-w><c-p>  |" Alternate between windows
nnoremap <leader>wo <c-w>o      |" window only
nnoremap <leader>wr <c-w>r      |" window rotate
nnoremap <leader>wx <c-w>x      |" window eXchange

" move windows around the screen
nnoremap <leader>wmj <c-w>J  |" move to bottom window
nnoremap <leader>wmk <c-w>K  |" move to top window
nnoremap <leader>wmh <c-w>H  |" move to left window
nnoremap <leader>wml <c-w>L  |" move to right window
nnoremap <leader>wmt <c-w>T  |" move current window to a tab

" resize windows
nnoremap <leader>wW <c-w>\|          |" Expand the width of the Window
nnoremap <leader>wH :resize 100<cr>  |" Expand the height of the Window
nnoremap <leader>w= <c-w>=           |" Make all windows equally high and wide
nnoremap <Up>    <c-w>-              |" Decrease current window height
nnoremap <Down>  <c-w>+              |" Increase current window height
" nnoremap <Left>  <c-w>>              |" Increase current window width
" nnoremap <Right> <c-w><              |" Decrease current window width

" windows switching
nnoremap <C-h> <c-w>h
nnoremap <C-j> <c-w>j
nnoremap <C-k> <c-w>k
nnoremap <C-l> <c-w>l
if has('nvim')
  tnoremap <C-h> <c-\><c-n><c-w>h
  tnoremap <C-j> <c-\><c-n><c-w>j
  tnoremap <C-k> <c-\><c-n><c-w>k
  tnoremap <C-l> <c-\><c-n><c-w>l
endif
" }}}2

" Tabs Mappings {{{2

" Opening and closing a tab
nnoremap <leader>tc :tabclose<cr>  |" close current tab
nnoremap <leader>tn :tabnew<cr>    |" create a new empty tab
nnoremap <leader>to :tabonly<cr>   |" close all others tab but this

" Moving betwen tabs
nnoremap [t :tabp<cr>              |" go to the previous tab
nnoremap ]t :tabn<cr>              |" go to the next tab
nnoremap [T :tabfirst<cr>          |" go to the first tab
nnoremap ]T :tablast<cr>           |" go to the last tab
nnoremap <leader>th :tabp<cr>      |" go to the previous tab
nnoremap <leader>tl :tabn<cr>      |" go to the next tab
nnoremap <leader>tH :tabfirst<cr>  |" go to the first tab
nnoremap <leader>tL :tablast<cr>   |" go to the last tab
nnoremap <A-Left> :tabp<cr>        |" go to the previous tab
nnoremap <A-Right> :tabn<cr>       |" go to the next tab
nnoremap <S-Left> :tabfirst<cr>    |" go to the first tab
nnoremap <S-Right> :tablast<cr>    |" go to the last tab

" Moving the tabs
nnoremap <leader>tmh :tabmove -1<cr>  |" move tab to the left
nnoremap <leader>tml :tabmove +1<cr>  |" move tab to the right
nnoremap <C-S-Left>tmh :tabmove -1<cr>  |" move tab to the left
nnoremap <C-S-Right>tml :tabmove +1<cr>  |" move tab to the right
" }}}2
"
" Neovim's Terminal Mappings {{{2
if has('nvim')
  tnoremap <Esc> <C-\><C-n>
  tnoremap <C-v><Esc> <Esc>
endif
" }}}2

" Vim Mappings {{{2
nnoremap <leader>ev :tabe $MYVIMRC<cr>  |" Edit vimrc file in a new tab
nnoremap <leader>sv :so $MYVIMRC<cr>    |" Source vimrc
" }}}2

" Python Mappings {{{2
if isdirectory('/opt/anaconda3')
  let g:python3_host_prog = '/opt/anaconda3/bin/python'
else
  let g:python3_host_prog = '/usr/local/anaconda3/bin/python'
endif
" }}}2

" }}}1

" Plugins Settings {{{1

" Plugin airline {{{2
" let g:airline#extensions#tabline#enabled = 1
" let g:airline#extensions#tabline#buffer_nr_show = 1
" let g:airline#extensions#tabline#formatter = 'unique_tail'
" }}} 2

" Plugin coc.nvim {{{2

let g:coc_global_extensions = [
  \ 'coc-actions',
  \ 'coc-css',
  \ 'coc-html',
  \ 'coc-emmet',
  \ 'coc-eslint',
  \ 'coc-explorer',
  \ 'coc-flutter',
  \ 'coc-git',
  \ 'coc-highlight',
  \ 'coc-json',
  \ 'coc-tabnine',
  \ 'coc-pairs',
  \ 'coc-prettier',
  \ 'coc-python',
  \ 'coc-snippets',
  \ 'coc-tsserver',
  \ 'coc-vimlsp',
  \ 'coc-yaml',
  \ 'coc-yank',
  \ ]

" Use tab for trigger completion with characters ahead and navigate.
" NOTE: Use command ':verbose imap <tab>' to make sure tab is not mapped by
" other plugin before putting this into your config.
inoremap <silent><expr> <TAB>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ coc#refresh()
inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"

function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction

" Use <c-space> to trigger completion.
inoremap <silent><expr> <c-space> coc#refresh()

" Use <cr> to confirm completion, `<C-g>u` means break undo chain at current
" position. Coc only does snippet and additional edit on confirm.
if has('patch8.1.1068')
  " Use `complete_info` if your (Neo)Vim version supports it.
  inoremap <expr> <cr> complete_info()["selected"] != "-1" ? "\<C-y>" : "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"
else
  imap <expr> <cr> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"
endif

" Use `[g` and `]g` to navigate diagnostics
nmap <silent> [c <Plug>(coc-diagnostic-prev)
nmap <silent> ]c <Plug>(coc-diagnostic-next)

" GoTo code navigation.
nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)

" Use K to show documentation in preview window.
nnoremap <silent> K :call <SID>show_documentation()<CR>

function! s:show_documentation()
  if (index(['vim','help'], &filetype) >= 0)
    execute 'h '.expand('<cword>')
  else
    call CocAction('doHover')
  endif
endfunction

" Highlight the symbol and its references when holding the cursor.
autocmd CursorHold * silent call CocActionAsync('highlight')

" Symbol renaming.
nmap <leader>re <Plug>(coc-rename)

" Formatting selected code.
xmap <leader>cf  <Plug>(coc-format-selected)
nmap <leader>cf  <Plug>(coc-format-selected)
vmap <leader>cf  <Plug>(coc-format-selected)

augroup mygroup
  autocmd!
  " Setup formatexpr specified filetype(s).
  autocmd FileType typescript,json setl formatexpr=CocAction('formatSelected')
  " Update signature help on jump placeholder.
  autocmd User CocJumpPlaceholder call CocActionAsync('showSignatureHelp')
augroup end

" Remap for do codeAction of selected region
" Example: `<leader>aap` for current paragraph
function! s:cocActionsOpenFromSelected(type) abort
  execute 'CocCommand actions.open ' . a:type . ' ' . g:cocActionsTmpPos[1] . ' ' . g:cocActionsTmpPos[2]
endfunction
xmap <silent> <leader>a :<C-u>execute 'CocCommand actions.open ' . visualmode()<CR>
nmap <silent> <leader>a :<C-u>let g:cocActionsTmpPos = getcurpos() \| set operatorfunc=<SID>cocActionsOpenFromSelected<CR>g@

" Apply AutoFix to problem on the current line.
nmap <leader>qf  <Plug>(coc-fix-current)

" Introduce function text object
" NOTE: Requires 'textDocument.documentSymbol' support from the language server.
xmap if <Plug>(coc-funcobj-i)
xmap af <Plug>(coc-funcobj-a)
omap if <Plug>(coc-funcobj-i)
omap af <Plug>(coc-funcobj-a)

" Use <TAB> for selections ranges.
" NOTE: Requires 'textDocument/selectionRange' support from the language server.
" coc-tsserver, coc-python are the examples of servers that support it.
nmap <silent> <TAB> <Plug>(coc-range-select)
xmap <silent> <TAB> <Plug>(coc-range-select)

" Add `:Format` command to format current buffer.
command! -nargs=0 Format :call CocAction('format')

" Add `:Fold` command to fold current buffer.
command! -nargs=? Fold :call CocAction('fold', <f-args>)

" Add `:OR` command for organize imports of the current buffer.
command! -nargs=0 OR   :call CocAction('runCommand', 'editor.action.organizeImport')

" Mappings using CoCList:

" Using CocList
nnoremap <silent> <leader>ll :<C-u>CocList<CR>
" Show all diagnostics.
nnoremap <silent> <leader>la  :<C-u>CocList diagnostics<cr>
" Show all buffers
nnoremap <silent> <leader>lb  :<C-u>CocList buffers<cr>
" Show commands.
nnoremap <silent> <leader>lc  :<C-u>CocList commands<cr>
" Manage extensionsleader
nnoremap <silent> <leader>le  :<C-u>CocList extensions<cr>
" Find symbol of culeader cdocument.
nnoremap <silent> <leader>lo  :<C-u>CocList outline<cr>
" Search workspace symbols.
nnoremap <silent> <leader>ls  :<C-u>CocList -I symbols<cr>
" Do default actionleaderncext item.
nnoremap <silent> <leader>cn  :<C-u>CocNext<CR>
" Do default actionleaderpcrevious item.
nnoremap <silent> <leader>cp  :<C-u>CocPrev<CR>
" Resume latest cocleader.c
nnoremap <silent> <leader>lr  :<C-u>CocListResume<CR>
" call Fold
nnoremap <silent> <leader>cF  :Fold<CR>zR

" Open yank list
nnoremap <silent> <leader>ly  :<C-u>CocList -A --normal yank<cr>
" flutter commands
nnoremap <silent> <leader>cf  :<C-u>CocList --input=flutter. --normal commands<CR>

" }}} 2

" Plugin python {{{2
if has('nvim')

  if isdirectory('/opt/anaconda3')
    let g:python3_host_prog = '/opt/anaconda3/bin/python'
  else
    let g:python3_host_prog = '/usr/local/anaconda3/bin/python'
  endif

endif
" }}}2

" Plugin Easy-align {{{2
xmap ga <Plug>(EasyAlign)
nmap ga <Plug>(EasyAlign)
" }}}2

" Plugin easy-motion {{{2
let g:EasyMotion_do_mapping = 0 " Disable default mappings

map <leader>/ <Plug>(incsearch-easymotion-/)
map <leader>? <Plug>(incsearch-easymotion-?)
map <leader>; <Plug>(incsearch-easymotion-stay)
" }}}2

" Plugin endwise {{{2
let g:endwise_no_mappings = 1
" }}}2

" Plugin FZF {{{2
map <C-p> :Files<cr>
nmap <C-p> :Files<cr>
nnoremap <leader>ff :files<cr>
nnoremap <leader>fF :GFiles<cr>
nnoremap <leader>fb :Buffers<cr>
nnoremap <leader>fa :Ag<cr>
nnoremap <leader>fl :Lines<cr>
nnoremap <leader>fL :Bines<cr>
nnoremap <leader>ft :Tags<cr>
nnoremap <leader>fT :BTags<cr>
nnoremap <leader>fc :Commits<cr>
nnoremap <leader>fC :BCommits<cr>
nnoremap <leader>fh :History<cr>
nnoremap <leader>fH :Helptags<cr>
nnoremap <leader>f: :History:<cr>
nnoremap <leader>f/ :History/<cr>
nnoremap <leader>fm :Marks<cr>
nnoremap <leader>fM :Maps<cr>

" Complete from open tmux panes (from @junegunn)
inoremap <expr> <C-x><C-t> fzf#complete( 'tmuxwords.rb -all-but-current --scroll 499 --min 5')

inoremap <expr> <C-x><C-k> fzf#complete ('cat /usr/share/dict/words')

" Mapping selecting mappings
nmap <leader><tab> <plug>(fzf-maps-n)
xmap <leader><tab> <plug>(fzf-maps-x)
omap <leader><tab> <plug>(fzf-maps-o)

" Insert mode completion
imap <c-x><c-k> <plug>(fzf-complete-word)
imap <c-x><c-f> <plug>(fzf-complete-path)
imap <c-x><c-j> <plug>(fzf-complete-file-ag)
imap <c-x><c-l> <plug>(fzf-complete-line)

" Advanced customization using autoload functions
inoremap <expr> <c-x><c-k> fzf#vim#complete#word({'left': '15%'})

" [Tags] Command to generate tags file
let g:fzf_tags_command = 'ctags -R'
" }}}2

" Plugin indentLine {{{2
let g:indentLine_setConceal = 0
" }}}2

" Plugin line-mover {{{2
let g:line_mover_key_up = '<A-k>'
let g:line_mover_key_down = '<A-j>'
" }}}2

" Plugin vCoolor {{{2
nnoremap <leader>p :VCoolor<cr>
" inoremap <leader>p :VCoolor<cr>
" }}}2

" Plugin Vim-go {{{2
let g:go_auto_type_info = 1
let g:go_auto_sameids = 1

let g:go_fmt_command = "goimports"

let g:go_highlight_build_constraints = 1
let g:go_highlight_extra_types = 1
let g:go_highlight_fields = 1
let g:go_highlight_functions = 1
let g:go_highlight_function_calls = 1
let g:go_highlight_generate_tags = 1
let g:go_highlight_methods = 1
let g:go_highlight_structs = 1
let g:go_highlight_types = 1
let g:go_highlight_operators = 1
" }}}2

" Plugin vim-indent-guides {{{2
let g:indent_guides_auto_co2ors = 0
" }}}2

" Plugin neoterm {{{2
nnoremap <leader>nc :<c-u>exec v:count.'Tclear'<cr>
nnoremap <leader>nC :<c-u>exec v:count.'Tclose'<cr>
nnoremap <leader>nk :<c-u>exec v:count.'Tkill'<cr>
nnoremap <leader>nn :<c-u>Tnew<cr>
nnoremap <leader>nq :<c-u>exec v:count.'T quit'<cr>

nnoremap <leader>ns :TREPLSendLine<cr>
vnoremap <leader>ns :TREPLSendSelection<cr>

nnoremap <leader>nb :<c-u>bo Tnew<cr><c-w>j
nnoremap <leader>nv :<c-u>vert Tnew<cr><c-w>l
nnoremap <leader>nt :<c-u>tabnew \| Tnew<cr>

nnoremap <leader>nl :<c-u>bo Tnext<cr>
nnoremap <leader>nh :<c-u>bo Tprevious<cr>
" }}}2

" }}}1

" Autocommands {{{1

" Reset all augroup for vimrc
augroup vimrc
  autocmd!

  " Delete trailing spaces before saving
  autocmd BufWritePre * :%s/\s\+$//ge

  " Auto save and Auto Reload
  autocmd FocusGained, BufEnter * :silent! !
  autocmd FocusLost, WinLeave * :silent! w
  autocmd CursorHold * silent! checktime

  " Number and Relative number
  autocmd FocusGained * :set relativenumber
  autocmd FocusLost * :set number norelativenumber

  autocmd InsertEnter * :set number norelativenumber
  autocmd InsertLeave * :set relativenumber

  " View save and restore is used for saving and restoring folding
  " autocmd BufWrite * mkview
  " autocmd BufRead * silent loadview

  " Disable flash error
  if has("gui_running")
    if has("x11")
      autocmd VimEnter * set vb t_vb= " gvim resets it, so I set it up again
    endif
  endif

augroup end

" Autocommands on Plugins {{{2
augroup vimrc

  " Plugin ansible=vim
  au BufRead,BufNewFile */ansible/*.yml set filetype=yaml.ansible

  " Plugin vim-indent-guides
  autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  ctermbg=234 guibg=#1c1c1c
  autocmd VimEnter,Colorscheme * :hi IndentGuidesEven ctermbg=235 guibg=#262626


augroup END
" }}}2
" }}}1

" FileType {{{1

augroup vimrc

  " FileType: Go {{{2
  autocmd FileType go setlocal ts=4 sts=4 sw=4 noexpandtab
  " autocmd FileType go setlocal listchars+=tab:\ \ , " don't show tabs for go files

  " Open :GoDeclsDir with ctrl-g
  autocmd FileType go nnoremap <C-g> :GoDeclsDir<cr>
  autocmd FileType go inoremap <C-g> <esc>:<C-u>GoDeclsDir<cr>

  autocmd FileType go nnoremap <leader>m <Plug>(go-run)
  autocmd FileType go nnoremap <leader>M <Plug>(go-run-tab)

  autocmd FileType go nnoremap <leader>b <Plug>(go-build)
  autocmd FileType go nnoremap <leader>te <Plug>(go-test)
  autocmd FileType go nnoremap <leader>co <Plug>(go-coverage-toggle)
  autocmd FileType go nnoremap <leader>i <Plug>(go-info)
  autocmd FileType go nnoremap <leader>n <Plug>(go-rename)

  autocmd FileType go nnoremap gD <Plug>(go-def-vertical)

  " Open documentation
  autocmd FileType go nnoremap <leader>do <Plug>(go-doc)
  autocmd FileType go nnoremap <leader>dv <Plug>(go-doc-vertical)
  autocmd FileType go nnoremap <leader>db <Plug>(go-doc-browser)

  " :GoAlternate commands :A, :AV, :AS and :AT
  autocmd Filetype go command! -bang A call go#alternate#Switch(<bang>0, 'edit')
  autocmd Filetype go command! -bang AV call go#alternate#Switch(<bang>0, 'vsplit')
  autocmd Filetype go command! -bang AS call go#alternate#Switch(<bang>0, 'split')
  autocmd Filetype go command! -bang AT call go#alternate#Switch(<bang>0, 'tabe')

  autocmd FileType go nnoremap <leader>af :A<cr>
  autocmd FileType go nnoremap <leader>at :AV<cr>
  autocmd FileType go nnoremap <leader>av :AV<cr>

  " gohtmltmpl
  autocmd BufNewFile,BufRead *.gohtml set filetype=gohtmltmpl
  autocmd FileType gohtmltmpl setlocal ts=2 sts=2 sw=2 expandtab

  " vim-delve
  autocmd FileType go nnoremap <leader>ab :DlvAddBreakpoint<cr>
  autocmd FileType go nnoremap <leader>ap :DlvAddTracepoint<cr>
  autocmd FileType go nnoremap <leader>ca :DlvClearAll<cr>
  autocmd FileType go nnoremap <leader>db :DlvDebug<cr>
  autocmd FileType go nnoremap <leader>dt :DlvTest<cr>
  autocmd FileType go nnoremap <leader>rb :DlvRemoveBreakpoint<cr>
  autocmd FileType go nnoremap <leader>rp :DlvRemoveTracepoint<cr>
  autocmd FileType go nnoremap <leader>tb :DlvToggleBreakpoint<cr>
  autocmd FileType go nnoremap <leader>tt :DlvToggleTracepoint<cr>
  " }}}2
  " }}}2

  " Filetype: Help {{{2
  autocmd FileType help wincmd J " Open help in bottom window
  " }}}2

  " Filetype: Java {{{2
  autocmd FileType java setlocal ts=4 sts=4 sw=4 noexpandtab
  " }}}2

  " Filetype: Vim {{{2
  autocmd FileType vim setlocal foldmethod=marker
  " }}}2

  " Filetype: Vue {{{2
  autocmd CursorMoved,CursorMovedI *vue call s:setVueFileType()
  " }}}2

augroup END
" }}}1

" Functions {{{1

" Editor Utilities {{{2
function! g:SaveCurrentBuffer()
  let buffer_name = @%

  execute "Format"
  w
endfunction

function! g:OpenNewTab()
  exec "tabnew"
  call OpenTerminal('terminal_1', "1")

  exec "normal \<c-h>"
endfunction

function! g:OpenSplitBuffer(name, vertical)
  if !bufexists(a:name)
    echo "Buffer doesn't exist"
    return
  endif

  if (a:vertical == 1)
    exec "vsplit"
  endif

  call OpenBuffer(a:name)
endfunction

function! g:OpenTabBuffer(name)
  if !bufexists(a:name)
    echo "Buffer doesn't exist"
    return
  endif

  exec "tabnew"

  call OpenBuffer(a:name)
endfunction


function! g:MarkBuffer(name)
  try
    exec "file!" . a:name
    echo ""
  catch
    echo "Buffer " . a:name . " already exist!"
  endtry
endfunction

function! g:OpenBuffer(name)
  if (expand('%') == a:name)
    return
  endif

  if !bufexists(a:name)
    echo "Buffer doesn't exist"
    return
  endif

  let buffer_number = bufnr(a:name)
  exec "buffer " . buffer_number
  echo ""
endfunction

function! g:OpenDownMarkedBuffers()
  let current_buffer = @%

  if matchstr(current_buffer, 'buffer_\d') == ''
    let buffer_number = bufnr("buffer_1")
    exec "buffer " . buffer_number
    return
  endif

  let id_buffer = matchstr(current_buffer, '\d')

  while id_buffer != 0
    let id_buffer = id_buffer - 1
    let buf_to_open = 'buffer_' . id_buffer

    if bufexists(buf_to_open)
      let buffer_number = bufnr(buf_to_open)
      exec "buffer " . buffer_number
      break
    endif
  endwhile

endfunction

function! g:OpenUpMarkedBuffers()
  let current_buffer = @%

  if matchstr(current_buffer, 'buffer_\d') == ''
    exec "edit buffer_1"
    return
  endif

  let id_buffer = matchstr(current_buffer, '\d')

  while id_buffer != 100
    let id_buffer = id_buffer + 1
    let buf_to_open = 'buffer_' . id_buffer

    if bufexists(buf_to_open)
      exec "edit " . buf_to_open
      break
    endif
  endwhile

endfunction
" }}}2

" }}}1
