---
- name: Linux - Make sure some base packages are installed
  pacman: name={{item}} state=present
  loop:
    - hddtemp
    - the_silver_searcher
    - unzip
  become: true

- name: Linux pacman - Make sure some base packages are installed
  pacman: name={{item}} state=present
  loop:
    - tk
  become: true

- name: Linux pacman - Make sure "chromium" is present
  pacman: name=chromium state=present
  become: true

- name: Linux pacman - Make sure "code (Visual Code)" is present
  pacman: name=code state=present
  become: true

- name: Linux pacman - Make sure "conky" is present
  pacman: name=conky state=present
  become: true

- name: Linux pacman - Make sure "ctags (exuberant-ctags)" is present
  pacman: name=ctags state=present
  become: true

- name: Linux pacman - Make sure "jdk8-openjdk" is present
  pacman: name=jdk8-openjdk state=present
  become: true

- name: Linux pacman - Make sure "go" is present
  pacman: name=go state=present
  become: true

- name: Linux pacman - Make sure "neovim" is present
  pacman: name=neovim state=present
  become: true

- name: Linux pacman - Make sure "nodejs-lts-dubnium" is present
  pacman: name=nodejs-lts-dubnium state=present
  become: true

- name: Linux pacman - Make sure "npm" is present
  pacman: name=npm state=present
  become: true

- name: Linux pacman - Make sure "tmux" is present
  pacman: name=tmux state=present
  become: true

- name: Linux pacman - Make sure "yad" is present
  pacman: name=yad state=present
  become: true

- name: Linux pacman - Make sure "zsh" is present
  pacman: name=zsh state=present
  become: true

- name: Linux - Install anaconda
  import_tasks: tasks/pkgs/anaconda3.yaml

- name: Linux Pacman - Install android-studio
  import_tasks: tasks/pkgs/android-studio.yaml

- name: Linux - Install pips
  import_tasks: tasks/pkgs/pips.yaml

- name: Linux - Install Docker
  import_tasks: tasks/pkgs/docker.yaml

- name: Linux - Install Go packages
  import_tasks: tasks/pkgs/go_pkgs.yaml

- name: Linux pacman - Link node files before installing packages.
  import_tasks: tasks/pkgs/node_link.yaml

- name: Linux - Install node packages
  import_tasks: tasks/pkgs/node_pkgs.yaml

- name: Linux - Install ruby
  import_tasks: tasks/pkgs/ruby.yaml

- name: Linux - Install ruby gems
  import_tasks: tasks/pkgs/ruby_gems.yaml

- name: Linux - Install snap
  import_tasks: tasks/pkgs/snap.yaml

- name: Linux - Install ohmyzsh
  import_tasks: tasks/pkgs/ohmyzsh.yaml

- name: Linux - Install virtualbox
  import_tasks: tasks/pkgs/virtualbox.yaml

- name: Linux - Install and configure pkgs for xorg
  import_tasks: tasks/pkgs/xorg.yaml


# On last because neovim need some packages installed before
- name: Linux - Install neovim's plugin
  import_tasks: tasks/pkgs/neovim_plugins.yaml

