- name: Mac or Linux - Verify if install FZF - Fuzzy Finder
  shell: fzf --version
  ignore_errors: yes
  register: fzf_version

- name: Mac or Linux - Install FZF - Fuzzy Finder
  shell: exec {{ dotfilespath }}/files/fzf/install.sh
  when: fzf_version.rc != 0

- name: Mac or Linux - Verify if install Ruby
  shell: rv=`awk -F '=' '/RUBY_VERSION=/{print $2}' {{ dotfilespath }}/files/ruby/install.sh`; ruby --version | grep $rv
  ignore_errors: yes
  register: ruby_version

- name: Mac or Linux - Install Ruby
  shell: exec {{ dotfilespath }}/files/ruby/install.sh
  when: ruby_version.rc != 0

- name: Mac or Linux - Install Node packages
  npm: name=tern global=yes state=present

- name: Mac or Linux - Install Python packages
  shell: exec {{ dotfilespath }}/files/python/install.sh

- name: Mac or Linux - Complete Installation for Vim
  shell: exec {{ dotfilespath }}/files/vim/configure.sh

- name: Mac or Linux -  Get the current shell
  command: echo $SHELL
  register: shell

- name: Mac or Linux -  Set the default shell to ZSH
  command: chsh -s /bin/zsh
  when: shell.stdout != "/bin/zsh"
  become: true

- name: Mac or Linux - Verify if install oh-my-zsh
  stat:
    path: ~/.oh-my-zsh
  register: ohmyzsh

- name: Mac or Linux - Install oh-my-zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  when: ohmyzsh.stat.exists != true
