- name: Mac or Linux - Verify if install FZF - Fuzzy Finder
  shell: fzf --version
  ignore_errors: yes
  register: fzf_version

- name: Mac or Linux - Install FZF - Fuzzy Finder
  shell: exec {{ dotfilespath }}/files/fzf/install.sh
  when: fzf_version.rc != 0

- name: Mac or Linux - Verify if install Ruby
  shell: rv=`head -1 {{ dotfilespath }}/files/ruby/install.sh | awk -F '=' '{print $2}'`; ruby --version | grep $rv
  ignore_errors: yes
  register: ruby_version

- name: Mac or Linux - Install Ruby
  shell: exec {{ dotfilespath }}/files/ruby/install.sh
  when: ruby_version.rc != 0

- name: Mac or Linux - Install Node packages
  npm: name=prettier global=yes state=present

- name: Mac or Linux - Complete Installation for Vim
  shell: exec {{ dotfilespath }}/files/vim/install.sh

- name: Mac or Linux -  Get the current shell
  command: echo $SHELL
  register: shell

- name: Mac or Linux -  Set the default shell to ZSH
  command: chsh -s /bin/zsh
  when: shell.stdout != "/bin/zsh"
  become: true
