- name: Link vimrc file
  file: src={{ dotfilespath }}/files/vim/vimrc
        dest=~/.vimrc
        state=link
        force=yes

- name: Link vimrc file in neovim's folder
  file: src={{ dotfilespath }}/files/vim/vimrc
        dest=~/.config.old/nvim/init.vim
        state=link
        force=yes

- name: Link vimrc file in neovim's folder
  file: src={{ dotfilespath }}/files/vim/coc-settings.json
        dest=~/.config.old/nvim/coc-settings.json
        state=link
        force=yes

- name: Link snippets to vim's folder
  file: src={{ dotfilespath }}/files/vim/snippets
        dest=~/.vim/snippets
        state=link
        force=yes
