#  _   _                  _                 _
# | | | |_   _ _ __  _ __| | __ _ _ __   __| |
# | |_| | | | | '_ \| '__| |/ _` | '_ \ / _` |
# |  _  | |_| | |_) | |  | | (_| | | | | (_| |
# |_| |_|\__, | .__/|_|  |_|\__,_|_| |_|\__,_|
#        |___/|_|
#

################
### MONITOR  ###
################

source = ~/.config/hypr/conf/monitor.conf

#################
### WORKSPACE ###
#################

source = ~/.config/hypr/conf/workspace.conf

###################
### MY PROGRAMS ###
###################

source = ~/.config/hypr/conf/variables.conf

#################
### AUTOSTART ###
#################

source = ~/.config/hypr/conf/autostart.conf

#############################
### ENVIRONMENT VARIABLES ###
#############################

source = ~/.config/hypr/conf/env.conf

#####################
### LOOK AND FEEL ###
#####################

source = ~/.config/hypr/conf/general.conf
source = ~/.config/hypr/conf/decoration.conf
source = ~/.config/hypr/conf/animation.conf
source = ~/.config/hypr/conf/layout.conf
source = ~/.config/hypr/conf/misc.conf


#############
### INPUT ###
#############

source = ~/.config/hypr/conf/input.conf

###################
### KEYBINDINGS ###
###################

source = ~/.config/hypr/conf/keybindings.conf

##############################
### WINDOWS AND WORKSPACES ###
##############################

source = ~/.config/hypr/conf/windowrule.conf
