---
- name: Go - Verify if install go
  stat:
    path: /opt/go
  register: stat_result

- name: Go - Download go tmp folder
  get_url:
    url: https://dl.google.com/go/{{ go_tar_file }}
    dest: /tmp/{{ go_tar_file }}
  when: stat_result.stat.exists == False

- name: Go - Extract go file to /opt
  unarchive:
    src: /tmp/{{ go_tar_file }}
    dest: /opt/
  become: true
  when: stat_result.stat.exists == False

- name: Go - Removing download file
  shell: warn=false rm /tmp/{{ go_tar_file }} 2>/dev/null
  when: stat_result.stat.exists == False
