---
- name: Go pkgs - Installing go pkgs
  shell: go get -u {{ item }}
  loop:
    - github.com/golangci/golangci-lint/cmd/golangci-lint
    - github.com/stamblerre/gocode
  environment:
    GOPATH: "{{ lookup('env', 'HOME') }}/code/go"
