---
- name: Go pkgs - Installing go pkgs
  shell: if [[ ! -d  "$HOME/code/go/src/{{ item.path }}" ]]; then go get -u {{ item.pkg }}; else echo "ok"; fi
  loop:
    - { path: github.com/golangci, pkg: github.com/golangci/golangci-lint/cmd/golangci-lint }
    - { path: github.com/stamblerre, pkg: github.com/stamblerre/gocode }
    - { path: github.com/cespare, pkg: github.com/cespare/reflex }
  environment:
    GOPATH: "{{ lookup('env', 'HOME') }}/code/go"
  args:
    executable: "/bin/bash"
  register: stat_result
  changed_when: stat_result.stdout != "ok"
