---
- name: Neovim - Verify if install neovim
  stat:
    path: /opt/neovim
  register: stat_result

- name: Neovim - Download neovim
  get_url:
    url: https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
    dest: /tmp
  when: stat_result.stat.exists == False

- name: Neovim - Change file permission for nvim.appimage to be executable
  file:
    path: /tmp/nvim.appimage
    mode: u+x
  when: stat_result.stat.exists == False

- name: Neovim - Extract nvim.appimage because this system doesn't use fuse
  shell: ./nvim.appimage --appimage-extract chdir=/tmp
  when: stat_result.stat.exists == False

- name: Neovim - Move extracted neovim's appimage to /opt/neovim
  shell: mv /tmp/squashfs-root /opt/neovim/
  when: stat_result.stat.exists == False
  become: true

- name: Neovim - Removing download file
  shell: warn=false rm /tmp/nvim.appimage
  when: stat_result.stat.exists == False

- name: Neovim - Removing extracting folder
  shell: warn=false rm -rf /tmp/squashfs-root
  when: stat_result.stat.exists == False

- name: Neovim - Link binary file to /usr/local/bin
  file: src=/opt/neovim/usr/bin/{{ item }}
        dest=/usr/local/bin/{{ item }}
        state=link
        force=yes
  loop:
    - nvim
  when: stat_result.stat.exists == False
  become: true
