---

- name: NerdFonts - Verify if install JetBrainsMono
  stat:
    path: "{{ lookup('env', 'HOME') }}/.local/share/fonts/NerdFonts/JetBrainsMono"
  register: stat_result

- name: NerdFonts - Create folder
  shell: warn=false mkdir -p ~/.local/share/fonts/NerdFonts/JetBrainsMono
  when: stat_result.stat.exists == False

- name: Download JetbrainsMono and extract it
  get_url:
    url: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/JetBrainsMono.zip
    dest: /tmp
  when: stat_result.stat.exists == False

- name: NerdFonts - Extract NerdFonts file to /tmp
  unarchive:
    src: /tmp/JetBrainsMono.zip
    dest: "{{ lookup('env', 'HOME') }}/.local/share/fonts/NerdFonts/JetBrainsMono"
  when: stat_result.stat.exists == False




- name: NerdFonts - Reload font cache
  shell: fc-cache
  when: stat_result.stat.exists == False
