---
- name: Node pkgs - Installing global node pkgs for macos
  npm: name=tern global=yes state=present
  loop:
    - neovim
    - tern
  when: os == "macos"

- name: Node pkgs - Installing global node pkgs for linux
  shell: /opt/node/bin/npm install -g {{ item }}
  environment:
    PATH: "/opt/node/bin:{{ ansible_env.PATH }}"
  loop:
    - neovim
    - tern
  when: os == "linux"
