---
- name: Oh my zsh - Get the current shell
  shell: echo $SHELL
  register: shell

- name: Oh my zsh - Set the default shell to ZSH for macos
  shell: chsh -s `which zsh`
  when: shell.stdout != "/bin/zsh" and os == "macos"
  become: true

# using sed to change the file, because had problem using chsh on wsl2
- name: Oh my zsh - Set the default shell to ZSH for linux
  shell: warn=false sudo sed -i "s@{{ lookup('env', 'HOME') }}.*@{{ lookup('env', 'HOME') }}\:`which zsh`@" /etc/passwd
  when: shell.stdout != "/bin/zsh" and os == "linux"
  become: true

- name: Oh my zsh - Verify if install oh-my-zsh
  stat:
    path: ~/.oh-my-zsh
  register: verify_ohmyzsh

- name: Oh my zsh - Install oh-my-zsh
  shell: warn=false curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | bash
  when: verify_ohmyzsh.stat.exists == False
