---
- name: Ruby - Verify if install rbenv
  stat:
    path: "{{ lookup('env', 'HOME') }}/.rbenv/versions/{{ ruby_version }}"
  register: stat_result

- name: Ruby - Download and install rbenv-installer
  shell: warn=false curl -fsSL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-installer | bash
  register: command_result
  failed_when: "'Please add it to PATH' not in command_result.stdout"
  when: stat_result.stat.exists == False

- name: Ruby - Install ruby {{ ruby_version }}
  shell: eval "$(rbenv init -)"; rbenv install {{ ruby_version }}
  environment:
    PATH: "{{ lookup('env', 'HOME') }}/.rbenv/bin:{{ ansible_env.PATH }}"
  when: stat_result.stat.exists == False

- name: Ruby - Define ruby {{ ruby_version }} as global for rbenv
  shell: eval "$(rbenv init -)"; rbenv global {{ ruby_version }}
  environment:
    PATH: "{{ lookup('env', 'HOME') }}/.rbenv/bin:{{ ansible_env.PATH }}"
  when: stat_result.stat.exists == False
