---
- name: Sdkman - Verify if install sdkman
  stat:
    path: "{{ lookup('env', 'HOME') }}/.sdkman"
  register: stat_result

- name: Sdkman - Install sdkman
  shell: warn=false export SDKMAN_DIR="/opt/sdkman" && curl -s "https://get.sdkman.io" | bash
  when: stat_result.stat.exists == False
  become: true

- name: Sdkman - Change owner and group for /opt/sdkman
  shell: warn=false chown -R {{ username }}:{{ usergroup }} /opt/sdkman
  when: stat_result.stat.exists == False
  become: true

- name : Sdkman - Install some pkgs
  shell: source "/opt/sdkman/bin/sdkman-init.sh"; sdk list {{ item }} | grep "> \*" ; if [[ $? = "1" ]]; then sdk install {{ item }}; else echo "ok"; fi
  ignore_errors: true
  loop:
    - java 11.0.5.j9-adpt
    - maven
    - micronaut
