---
- name: Sdkman - Verify if install sdkman
  stat:
    path: "{{ lookup('env', 'HOME') }}/.sdkman"
  register: stat_result

- name: Sdkman - Install sdkman
  shell: warn=false export SDKMAN_DIR="{{ lookup('env', 'HOME') }}/.sdkman" && curl -s "https://get.sdkman.io" | bash
  when: stat_result.stat.exists == False

- name: Sdkman - Install some pkgs
  shell: source "{{ lookup('env', 'HOME') }}/.sdkman/bin/sdkman-init.sh"; sdk list {{ item }} | grep "> \*" ; if [[ $? = "1" ]]; then sdk install {{ item }}; else echo "ok"; fi
  ignore_errors: true
  loop:
    - java 11.0.10-open
    - maven
    - micronaut
