---
- name: Squirrel SQL - Verify if install Squirrel SQL
  stat:
    path: /opt/squirrel-sql
  register: stat_result

- name: Squirrel SQL - Download Squirrel SQL
  get_url:
    url: https://razaoinfo.dl.sourceforge.net/project/squirrel-sql/1-stable/{{ squirrel_sql_version }}-plainzip/{{ squirrel_sql_zip_file }}
    dest: /tmp
  when: stat_result.stat.exists == False

- name: Squirrel SQL - Extract Squirrel SQL file to /opt
  unarchive:
    src: /tmp/{{ squirrel_sql_zip_file }}
    dest: /tmp
  become: true
  when: stat_result.stat.exists == False

- name: Squirrel SQL - Move Squirrel SQL folder to /opt as /opt/squirrel-sql
  shell: warn=false mv /tmp/{{ squirrel_sql_file }} /opt/squirrel-sql
  become: true
  when: stat_result.stat.exists == False

- name: Squirrel SQL - Removing download file
  shell: warn=false rm /tmp/{{ squirrel_sql_zip_file }} 2>/dev/null
  when: stat_result.stat.exists == False

- name: Squirrel SQL - Verify if fix the script to start the Squirrel SQL outside its folder
  shell: grep opt /opt/squirrel-sql/squirrel-sql.sh
  ignore_errors: true
  register: verify_script

- name: Squirrel SQL - Fix the SQUIRREL_SQL_HOME
  shell: sed -i -e '0,/SQUIRREL_SQL_HOME/ s,SQUIRREL_SQL_HOME=.*,SQUIRREL_SQL_HOME=/opt/squirrel-sql/,' /opt/squirrel-sql/squirrel-sql.sh
  when: verify_script.rc == 1
  become: true

- name: Squirrel SQL - Set the file to be executable
  shell: warn=false chmod +x /opt/squirrel-sql/squirrel-sql.sh
  when: verify_script.rc == 1
  become: true

- name: Squirrel SQL - Link binary file to /usr/local/bin
  file: src=/opt/squirrel-sql/squirrel-sql.sh
        dest=/usr/local/bin/squirrel-sql.sh
        state=link
        force=yes
  when: stat_result.stat.exists == False
  become: true
