---
- name: Linux pacman - Install vscode extensions
  shell: code --install-extension {{ item }}
  loop:
    - dbaeumer.vscode-eslint
    - naco-siren.gradle-language
    - pivotal.vscode-spring-boot
    - redhat.vscode-openshift-java-pack
    - shengchen.vscode-checkstyle
    - usernamehw.errorlens
    - vscodevim.vim
    - vscjava.vscode-java-pack
    - vscjava.vscode-maven
    - vscjava.vscode-spring-boot-dashboard
    - vscjava.vscode-spring-initializr
    - youmaycallmev.vscode-java-saber


