set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

"-------------------------------------------------------------------------------
"  Vundle manage Vundle, required
"-------------------------------------------------------------------------------
Plugin 'gmarik/Vundle.vim'

"-------------------------------------------------------------------------------
"  Colors and themes
"-------------------------------------------------------------------------------
Plugin 'tomasr/molokai'
Plugin 'bling/vim-airline'

"-------------------------------------------------------------------------------
"  Git
"-------------------------------------------------------------------------------
Plugin 'tpope/vim-fugitive'
Plugin 'gregsexton/gitv'
Plugin 'mattn/gist-vim'
Plugin 'mattn/webapi-vim' " dependency for gist-vim

"-------------------------------------------------------------------------------
"  Go
"-------------------------------------------------------------------------------
Plugin 'fatih/vim-go'

"-------------------------------------------------------------------------------
"  Html
"-------------------------------------------------------------------------------
Plugin 'othree/html5.vim'
Plugin 'mattn/emmet-vim'

"-------------------------------------------------------------------------------
"  Javascript
"-------------------------------------------------------------------------------
Plugin 'pangloss/vim-javascript'
Plugin 'burnettk/vim-angular'
Plugin 'kchmck/vim-coffee-script'"

"-------------------------------------------------------------------------------
"  Ruby and Rails
"-------------------------------------------------------------------------------
Plugin 'vim-ruby/vim-ruby'
Plugin 'tpope/vim-rails'
Plugin 'tpope/vim-rake'
Plugin 'thoughtbot/vim-rspec'

"-------------------------------------------------------------------------------
"  Search & Navigation
"-------------------------------------------------------------------------------
Plugin 'scrooloose/nerdtree'
Plugin 'justinmk/vim-sneak'
Plugin 'rking/ag.vim'
Plugin 'ctrlpvim/ctrlp.vim'
Plugin 'Valloric/YouCompleteMe'
Plugin 'sjl/gundo.vim'

"-------------------------------------------------------------------------------
"  Snippets
"-------------------------------------------------------------------------------
Plugin 'SirVer/ultisnips'
Plugin 'honza/vim-snippets'

"-------------------------------------------------------------------------------
"  Syntax Checker
"-------------------------------------------------------------------------------
Plugin 'scrooloose/syntastic'

"-------------------------------------------------------------------------------
"  Tpope Utilities
"-------------------------------------------------------------------------------
Plugin 'tpope/vim-abolish'
Plugin 'tpope/vim-commentary'
Plugin 'tpope/vim-dispatch'
Plugin 'tpope/vim-eunuch'
Plugin 'tpope/vim-repeat'
Plugin 'tpope/vim-speeddating'
Plugin 'tpope/vim-surround'
Plugin 'tpope/vim-unimpaired'

"-------------------------------------------------------------------------------
"  Text & Utilities
"-------------------------------------------------------------------------------
Plugin 'jiangmiao/auto-pairs'
Plugin 'junegunn/vim-easy-align'
Plugin 'majutsushi/tagbar'

"-------------------------------------------------------------------------------
"  Tmux integration
"-------------------------------------------------------------------------------
Plugin 'benmills/vimux'
Plugin 'christoomey/vim-tmux-navigator'

call vundle#end()
filetype plugin indent on

" override default configurations
source $HOME/.vim/colors.vim
source $HOME/.vim/config.vim
source $HOME/.vim/shortcuts.vim
source $HOME/.vim/autocommands.vim
source $HOME/.vim/functions.vim
source $HOME/.vim/plugins.vim
