---
- hosts: localhost

  pre_tasks:
    - include: tasks/os_mac.yaml
      when: ansible_distribution == "MacOSX"

    - include: tasks/os_linux.yaml
      when: ansible_distribution == "\"bunsenlabs\""

    - include: tasks/os_mac_linux.yaml

  tasks:
    - include: tasks/configs/git.yaml
    - include: tasks/configs/ohmyzsh.yaml
    - include: tasks/configs/ruby.yaml
    - include: tasks/configs/tmux.yaml
    - include: tasks/configs/vim.yaml
