---
- hosts: localhost

  vars_files:
    - vars.yaml

  pre_tasks:
    - import_tasks: tasks/pkgs/opt.yaml

  tasks:
    - import_tasks: tasks/os_linux_pacman.yaml

    - import_tasks: tasks/pkgs/git_link.yaml
    - import_tasks: tasks/pkgs/idea_link.yaml
    - import_tasks: tasks/pkgs/fish_link.yaml
    - import_tasks: tasks/pkgs/python_link.yaml
    - import_tasks: tasks/pkgs/ruby_link.yaml
    - import_tasks: tasks/pkgs/tmux_link.yaml
    - import_tasks: tasks/pkgs/vim_link.yaml
