---
- hosts: localhost

  vars_files:
    - vars.yaml

  pre_tasks:
    # - import_tasks: tasks/os_mac.yaml
    #   when: os == "macos"

    # - import_tasks: tasks/os_linux.yaml
    #   when: (os == "linux") and (os_distro != "manjaro")

    - import_tasks: tasks/os_linux_pacman.yaml
      when: (os == "linux") and (os_distro == "manjaro")

  tasks:
    - import_tasks: tasks/pkgs/git_link.yaml
    - import_tasks: tasks/pkgs/idea_link.yaml
    - import_tasks: tasks/pkgs/fish_link.yaml
    - import_tasks: tasks/pkgs/python_link.yaml
    - import_tasks: tasks/pkgs/ruby_link.yaml
    - import_tasks: tasks/pkgs/tmux_link.yaml
    - import_tasks: tasks/pkgs/vim_link.yaml
