---
- name: Pips - Installing pips for macos
  shell: "/usr/local/anaconda3/bin/pip install {{ item.extra_args }} {{ item.name }}"
  loop: "{{ pips }}"
  when: os == "macos"

- name: Pips - Installing pips for linux
  shell: "/opt/anaconda3/bin/pip install {{ item.extra_args }} {{ item.name }}"
  loop: "{{ pips }}"
  when: os == "linux"
